{% set name = "MEDM" %}
{% set version = "3_1_21" %}

package:
  name: epics-{{ name|lower }}
  version: {{ version|replace('_','.') }}

source:
  url: https://github.com/epics-extensions/medm/archive/MEDM{{ version }}.tar.gz
  sha256: 55ab4970a73ba467ae1a71adba8ea7a185d15922d074f28c435f165d17aacb36
  patches:
    # don't statically compile to libraries from macports macOS
    - no-macports.patch  # [osx]

build:
  number: 0
  # no openmotif on windows
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - make
  host:
    - epics-base
    - epics-extensions
    - openmotif-dev
    - xorg-libx11  # [unix]
    - xorg-libxext  # [unix]
    - xorg-libxmu  # [unix]
    - xorg-libxp  # [unix]
    - xorg-libxt  # [unix]
  run:
    - epics-base
    - openmotif
    - xorg-libx11  # [unix]
    - xorg-libxext  # [unix]
    - xorg-libxmu  # [unix]
    - xorg-libxp  # [unix]
    - xorg-libxt  # [unix]

test:
  commands:
    - medm -h

about:
  home: https://epics.anl.gov/extensions/medm/
  dev_url: https://github.com/epics-extensions/medm/
  doc_url: https://epics.anl.gov/EpicsDocumentation/ExtensionsManuals/MEDM/MEDM.html
  license: EPICS
  license_file: LICENSE
  summary: Motif Editor and Display Manager
  description: |
    MEDM is a graphical user interface tool for designing and implementing control
    screens for EPICS-based control systems. Displays contain graphical objects that
    can display and/or change the values of EPICS process variables using the
    Channel Access network protocol. Supported graphical objects include buttons,
    meters, sliders, text displays/entries, and graphs.

    MEDM has two modes of operation, EDIT and EXECUTE. Displays are created and
    edited in EDIT mode, and run in EXECUTE mode.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - pthomasj
